name: graphist
description: Adds graph capabilities to Flutter applications.
version: 0.2.0
homepage: https://github.com/amin-ahmadi-com/graphist

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.2
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  mockito: ^5.3.2

flutter:
